### ISSUE TITLE
[Request]adding a new wm flavor

### ISSUE THREAD

**Issue by alavaelian** [peux-os/pos_repo#1]
i am asking for a new flavor with  a very good dwm config that is called  chadwm https://github.com/siduck/chadwm

**Comment by DN-debug** [comment]
Hey, just saw this, I dont get notifications from these repos ( i should archive this lol ) . Anyways, I guess we've already discussed it on Telegram, hence I will be closing this issue. Let me know via telegram if anything else comes up. Thanks.
